export const m = {
  taihedian:'Taihe hall, located in the Palace Museum and standing in the center of the Forbidden City, is one of the three great halls in the East. It is the most regulated ancient palace building in China and the place where the emperor held major ceremonies.  The hall of Supreme Harmony was completed in 1420. The hall of Supreme Harmony was rebuilt and preserved in the reign of Emperor Kangxi of the Qing Dynasty.',
  garden:'The imperial garden is located on the central axis of the Forbidden City in Beijing. It was called the Palace back garden in the Ming Dynasty. Founded in 1420, it still retains the basic pattern when it was first built. Qin\'an hall, the main building in the park, is of the double eaved roof type. With it as the center, pavilions and pavilions are spread to the front and both sides. The garden forms an evergreen landscape.',
  zhonghedian:'Zhonghe hall, founded in 1420, was called "Huagai hall" in the early Ming Dynasty. Later, it was caught in a fire and renamed as "Zhongji hall" after renovation. Now, the internal components of the ceiling still have the ink of "Zhongji hall" of the Ming Dynasty. In 1644, the Qing Royal family moved into the Forbidden City. The following year, the Zhongji hall was changed to the Zhonghe hall. In the three halls, only this room can be used for the emperor to think quietly.',
  taihemen:'Taihe gate is the largest gate in the Forbidden City and the main gate of the outer court palace. Taihe gate was built in the 18th year of Yongle in the Ming Dynasty and was called Fengtian gate at that time. It was burned down in the 14th year of the reign of Emperor Guangxu of the Qing Dynasty and rebuilt the following year.The Taihe gate is covered with double eaves on the top of the mountain, and under it is a white marble base. ',
  baohedian:'Baohe hall, a traditional palace building in the Ming and Qing Dynasties, is a temple style building in the Forbidden City in Beijing. It was completed in 1420, the 18th year of Yongle in the Ming Dynasty, and was burned and rebuilt several times. Today, the main beam frame is still a building in the Ming Dynasty.',
  qianqingmen:'Qianqing gate is the main gate of the inner court of the Forbidden City. It was built in 1420 and rebuilt in 1655. The area behind the Qianqing gate is the residence and living area of the empress and his concubines and the prince. The main gate of the three palaces (Qianqing palace, Jiaotai palace and Kunning Palace) of the inner court was the place where the emperor "listened to politics at the imperial gate" in the Qing Dynasty.',
  qianqinggong:'Qianqing palace, one of the three palaces behind the inner court, the Palace Museum, No. 4 Jingshan front street, Dongcheng District, Beijing. It was first built in 1420, the 18th year of Yongle in the Ming Dynasty. It was rebuilt in the Ming and Qing dynasties after being burned several times. The existing building was built in 1798, the third year of Jiaqing in the Qing Dynasty. The building covers an area of about 1400 square meters.',
  jiaotaidian:'Jiaotai hall, a palace building of the Ming and Qing Dynasties with a long history, is one of the three palaces behind the inner court of the Imperial Palace in Beijing. It is located between the Qianqing palace and the Kunning palace. The name of the hall is taken from the book of changes, which means "harmony between heaven and earth, Kangtai and happiness".',
  kunninggong:'Located in the north of Jiaotai hall in the Forbidden City, Kunning palace is one of the three palaces behind the Imperial Palace in Beijing, behind the Jiaotai hall. The name of the palace of earthly tranquility comes from the Tao Te Ching: "in the past, those who got the one, the heaven got a clear, the earth got a peaceful, the God got a spirit, the valley got a surplus, all things got a life, and the Marquis and the king thought the world was right.',
  kunningmen:'The Kunning gate is the north gate in the middle of the backstage steps of the Kunning palace, which connects the imperial garden in the north. In the early Ming Dynasty, Kunning gate was set in the north of Qin\'an Hall of imperial garden, namely shunzhen gate. In 1535, the Guangyun gate in the middle of the North Wai corridor behind the Kunning palace was rebuilt and renamed Kunning gate, which continued until the Qing Dynasty. The Kunning gate was rebuilt in 1655.',
}
